# Generated by Django 5.2.1 on 2025-06-05 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptBookDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_mobile', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('deposit_center', models.CharField(max_length=100)),
                ('member_email', models.EmailField(blank=True, max_length=254)),
                ('center_type', models.CharField(max_length=100)),
                ('member_code', models.CharField(blank=True, max_length=50)),
                ('narration', models.CharField(blank=True, max_length=200)),
                ('member_name', models.CharField(max_length=100)),
                ('collected_receipt', models.CharField(blank=True, max_length=100)),
                ('member_profile_id', models.CharField(blank=True, max_length=100)),
                ('receipt_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('address', models.TextField()),
                ('extra_cash_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('extra_mt_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('city', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
