# Generated by Django 5.2.1 on 2025-06-05 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptbookdeposit',
            name='deposit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='receiptbookdeposit',
            name='withdrawal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
