# Generated by Django 5.2.1 on 2025-06-05 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger_app', '0002_receiptbookdeposit_deposit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receiptbookdeposit',
            name='address',
        ),
        migrations.RemoveField(
            model_name='receiptbookdeposit',
            name='center_type',
        ),
        migrations.RemoveField(
            model_name='receiptbookdeposit',
            name='city',
        ),
        migrations.RemoveField(
            model_name='receiptbookdeposit',
            name='collected_receipt',
        ),
        migrations.RemoveField(
            model_name='receiptbookdeposit',
            name='deposit',
        ),
        migrations.RemoveField(
            model_name='receiptbookdeposit',
            name='deposit_center',
        ),
        migrations.RemoveField(
            model_name='receiptbookdeposit',
            name='extra_cash_amount',
        ),
        migrations.RemoveField(
            model_name='receiptbookdeposit',
            name='extra_mt_amount',
        ),
        migrations.RemoveField(
            model_name='receiptbookdeposit',
            name='member_code',
        ),
        migrations.RemoveField(
            model_name='receiptbookdeposit',
            name='member_email',
        ),
        migrations.RemoveField(
            model_name='receiptbookdeposit',
            name='member_profile_id',
        ),
        migrations.RemoveField(
            model_name='receiptbookdeposit',
            name='receipt_amount',
        ),
        migrations.RemoveField(
            model_name='receiptbookdeposit',
            name='withdrawal',
        ),
        migrations.AddField(
            model_name='receiptbookdeposit',
            name='closing_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='receiptbookdeposit',
            name='code',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='receiptbookdeposit',
            name='credit_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='receiptbookdeposit',
            name='debit_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='receiptbookdeposit',
            name='month',
            field=models.CharField(choices=[('April', 'APRIL'), ('May', 'MAY'), ('June', 'JUNE'), ('July', 'JULY'), ('August', 'AUGUST'), ('September', 'SEPTEMBER'), ('October', 'OCTOBER'), ('November', 'NOVEMBER'), ('December', 'DECEMBER'), ('January', 'JANUARY'), ('February', 'FEBRUARY'), ('March', 'MARCH')], default='April', max_length=20),
        ),
        migrations.AddField(
            model_name='receiptbookdeposit',
            name='pending_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='receiptbookdeposit',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='receiptbookdeposit',
            name='year',
            field=models.CharField(choices=[('23-24', '23-24'), ('24-25', '24-25'), ('25-26', '25-26')], default='24-25', max_length=10),
        ),
        migrations.AlterField(
            model_name='receiptbookdeposit',
            name='narration',
            field=models.TextField(blank=True),
        ),
    ]
