# Generated by Django 5.1.3 on 2025-06-05 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger_app', '0003_remove_receiptbookdeposit_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptbookdeposit',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
