# Generated by Django 5.1.3 on 2026-03-11 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger_app', '0004_receiptbookdeposit_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receiptbookdeposit',
            name='status',
        ),
    ]
